(let ((buf (get-buffer-create "*demo-buffer*")))
  (set-buffer buf)
  (insert "Hello ")
  (insert "World!")
  (print (point))
  (goto-char 7)
  (insert "beautiful ")
  (print (point))
  (print (point-min))
  (print (point-max)))
