;;; demo_markers.el --- Test suite for markers, deletions, and movements

;; 1. Marker Lifecycle & Typing
(message "=== 1. Marker Lifecycle ===")
(let ((m (make-marker)))
  (print (markerp m))
  (print (marker-buffer m))
  (print (marker-position m))
  (let ((buf (get-buffer-create "*marker-test-buffer*")))
    (set-buffer buf)
    (insert "Hello World")
    (set-marker m 6 buf)
    (print (marker-position m))
    (print (eq (marker-buffer m) buf))
    (let ((m2 (copy-marker m)))
      (print (marker-position m2))
      (print (eq (marker-buffer m2) buf))
      (print (markerp m2)))))

;; 2. Marker Auto-Adjustment
(message "=== 2. Marker Auto-Adjustment ===")
(let ((buf (get-buffer-create "*adjust-test*")))
  (set-buffer buf)
  (insert "abcde")
  (let ((m1 (make-marker))
        (m2 (make-marker)))
    (set-marker m1 3 buf)
    (set-marker m2 5 buf)
    (goto-char 1)
    (insert "xyz")
    (print (marker-position m1))
    (print (marker-position m2))
    (delete-region 6 8)
    (print (marker-position m1))
    (print (marker-position m2))
    (print (buffer-substring (point-min) (point-max)))))

;; 3. Movements & Deletions
(message "=== 3. Movements & Deletions ===")
(let ((buf (get-buffer-create "*move-test*")))
  (set-buffer buf)
  (insert "Line 1\nLine 2\nLine 3")
  (goto-char 1)
  (forward-char 3)
  (print (point))
  (backward-char 2)
  (print (point))
  (beginning-of-line)
  (print (point))
  (end-of-line)
  (print (point))
  (forward-line 1)
  (print (point))
  (beginning-of-line)
  (print (point))
  (delete-char 4)
  (print (buffer-substring (point-min) (point-max)))
  (erase-buffer)
  (print (length (buffer-substring (point-min) (point-max)))))
